name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  USERNAME :  ${{ secrets.DOCKER_USERNAME }}
  PASSWORD :  ${{ secrets.DOCKER_TOKEN }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          registry: docker.io
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
    
    - name: Build and push the Docker image
      run: |
        docker build -t mineos . 
        docker tag mineos:latest andino66/mineos:latest
        docker push andino66/mineos:latest
