name: Publish Docker Image to Docker Hub
on:
  release:
    types:
      - created
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        run: |
          docker build -t mineos .
          docker tag mineos:latest andino66/mineos:latest
          docker push andino66/mineos:latest
